# Build examples with Platformio
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# https://docs.platformio.org/en/latest/integration/ci/github-actions.html

name: PlatformIO CI

on:
  push:
    branches: [ master, v2 ]
  pull_request:
    branches: [ master, v2 ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        code:
          - "."

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Platformio
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        pio update
    - name: Run PlatformIO
      run: |
        pio run -e espem -e espem_debug -e espem_core202
#      env: 
#        PLATFORMIO_CI_SRC: ${{ matrix.code }}
#      run: |
#        pio ci -c ${{ matrix.code }}/platformio.ini