# Build examples with Platformio
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# https://docs.platformio.org/en/latest/integration/ci/github-actions.html

name: PlatformIO CI

on:
  workflow_dispatch:      # Manual start
  push:
    branches: [ master, feat ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**.c'
      - '**.ini'
      - '**.yml'
  pull_request:
    branches: [ master]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**.c'
      - '**.ini'
      - '**.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.repository == 'vortigont/espem'
    strategy:
      matrix:
        code:
          - "."

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Platformio
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          #platformio run -t buildfs
          #platformio pkg update
      - name: Run PlatformIO
        run: |
          pio run -e espem -e espem_debug
#      env: 
#        PLATFORMIO_CI_SRC: ${{ matrix.code }}
#      run: |
#        pio ci -c ${{ matrix.code }}/platformio.ini
